version: "3.9"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "500k"
    max-file: "20"

x-entrypoint: &default-entrypoint
  entrypoint: >
    /bin/sh -c "
      set -e
      echo Waiting TTY interation..
      /bin/bash || exit 0
    "

services:
  compyler:
    container_name: compyler
    build:
      context: .
      dockerfile: Dockerfile
    <<: *default-entrypoint
    stdin_open: true
    tty: true
    restart: on-failure
    logging: *default-logging
    networks: ["compyler"]

networks:
  compyler:
